services:
  app:
    image: microservice-js:latest
    container_name: microservice-js
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - shared_network


networks:
  shared_network:
    external: true